#!/bin/sh

# generates zathura configuration file

# added from 
# https://www.reddit.com/r/unixporn/comments/8giij5/guide_defining_program_colors_through_xresources/

get_xres() {
    xrdb -query | grep $1 | awk '{print $2}'
}

cat <<CONF
set completion-bg "$(get_xres color0:)"
set completion-fg "$(get_xres color7:)"
set completion-group-bg "$(get_xres color0:)"
set completion-group-fg "$(get_xres color2:)"
set completion-highlight-bg "$(get_xres color7:)"
set completion-highlight-fg "$(get_xres color0:)"
set default-bg "$(get_xres color0:)"
set default-fg "$(get_xres color7:)"
set inputbar-bg "$(get_xres color0:)"
set inputbar-fg "$(get_xres color7:)"
set notification-bg "$(get_xres color0:)"
set notification-fg "$(get_xres color7:)"
set notification-error-bg "$(get_xres color1:)"
set notification-error-fg "$(get_xres color7:)"
set notification-warning-bg "$(get_xres color1:)"
set notification-warning-fg "$(get_xres color7:)"
set statusbar-bg "$(get_xres color0:)"
set statusbar-fg "$(get_xres color7:)"
set index-bg "$(get_xres color0:)"
set index-fg "$(get_xres color7:)"
set index-active-bg "$(get_xres color7:)"
set index-active-fg "$(get_xres color0:)"
set render-loading-bg "$(get_xres color0:)"
set render-loading-fg "$(get_xres color7:)"

set recolor-lightcolor "$(get_xres color0:)"
set recolor-darkcolor "$(get_xres color7:)"

set font "monospace 13"
set window-title-home-tilde true
set statusbar-basename true
set selection-clipboard clipboard


map <Space> navigate next
map <C-Space> navigate previous 

CONF
