#!/bin/sh

# adapted from
# https://github.com/I-LeCorbeau/dotfiles/blob/master/.local/bin/statusbar.sh

usb() {
	usb1=$(lsblk -la | awk '/sdb2/ { print $1 }')
	usb1mounted=$(lsblk -la | awk '/sdb2/ { print $7 }')

	if [ "$usb1" ]; then
		if [ -z "$usb1mounted" ]; then
			echo " |"
		else
			echo " $usb1 |"
		fi
	fi
}

ram() {
	mem=$(free -h | awk '/Mem:/ { print $3 }' | cut -f1 -d 'i')
	echo " $mem"
}

cpu() {
	read -r cpu a b c previdle rest < /proc/stat
	prevtotal=$((a+b+c+previdle))
	sleep 0.5
	read -r cpu a b c idle rest < /proc/stat
	total=$((a+b+c+idle))
	cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
	echo " $cpu%"
}

updates() {
	updates=$(checkupdates | wc -l)
	packages=$(pacman -Q | wc -l)
	if [ "$updates" -ge 30 ]; then
		echo " $packages"
	else
		echo " $packages"
	fi
}

network() {
	conntype=$(ip route | awk '/default/ { print substr($5,1,1) }')

	if [ -z "$conntype" ]; then
		echo " down"
	elif [ "$conntype" = "e" ]; then
		echo " up"
	elif [ "$conntype" = "w" ]; then
		echo " up"
	elif [ "$conntype" = "l" ]; then
		echo " vpn"
	fi
}

volume() {
	muted=$(pactl list sinks | awk '/Mute:/ { print $2 }')
	vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'FNR == 1 { print $5 }' \
		| cut -f1 -d '%')

	if [ "$muted" = "yes" ]; then
		echo " "
	else
		if [ "$vol" -ge 65 ]; then
			echo " $vol%"
		elif [ "$vol" -ge 40 ]; then
			echo " $vol%"
		elif [ "$vol" -ge 0 ]; then
			echo " $vol%"	
		fi
	fi

}

battery () {
    charge=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

	if [ "$status" = "Charging" ]; then
		status_sign="+"
	else
		status_sign=""
	fi

	if [ "$charge" -ge 95 ]; then
		echo "$status_sign $charge%"
	elif [ "$charge" -ge 75 ]; then
		echo "$status_sign $charge%"
	elif [ "$charge" -ge 50 ]; then
		echo "$status_sign $charge%"
	elif [ "$charge" -ge 25 ]; then
		echo "$status_sign $charge%"	
	elif [ "$charge" -ge 0 ]; then
		echo "$status_sign $charge%"
	fi
}

clock() {
	date=$(date +"%d %b %Y")
	time=$(date +"%H:%M")

	echo "$date $time"
}

while true; do
	xsetroot -name " $(usb) $(ram) | $(cpu) | $(updates) | $(network) | $(volume) | $(battery) | $(clock) "
	sleep 5
done
